Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
       path('admin/', admin.site.urls),
       path('', include('app.urls'),),
       path('', include('users.urls'),),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path

from app.views import  ArticleListView,ArticleDetailView,ArticleCreateView,ArticleUpdateView,ArticleDeleteView

urlpatterns = [
    #path('', views.index, name='index'),


    path('', ArticleListView.as_view(), name='article_list'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('article/new/', ArticleCreateView.as_view(), name='article_new'),
    path('article/<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_edit'),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

users/urls.py
from django.urls import path
from .views import connexion,deconnexion

urlpatterns = [
       path('login/',connexion,name='login'),
       path('logout/', deconnexion, name='logout'),
]

app/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    titre = models.CharField(max_length=200)
    contenu = models.TextField()
    date_publication = models.DateTimeField(auto_now_add=True)
    auteur = models.CharField(max_length=100)
    image = models.ImageField(upload_to="articles_images/", blank=True, null=True)

    def __str__(self):
        return self.titre

users/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from app.models import Article
from django.urls import reverse_lazy

# Create your views here.



# Liste Article
class ArticleListView(ListView):
    model = Article
    template_name = "post.html"
    context_object_name = "articles"
    paginate_by = 4

class ArticleDetailView(DetailView):
    model = Article
    template_name = "details.html"

class ArticleCreateView(CreateView):
    model = Article
    fields = ['titre', 'contenu', 'auteur', 'image']
    template_name = "creer.html"
    success_url = reverse_lazy('article_list')

# Modification Article
class ArticleUpdateView(UpdateView):
    model = Article
    fields = ['titre', 'contenu', 'auteur', 'image']
    template_name = "modifier.html"
    success_url = reverse_lazy('article_list')


# Suppression Article
class ArticleDeleteView(DeleteView):
    model = Article
    fields = ['titre']
    template_name = "supprimer.html"
    success_url = reverse_lazy('article_list')

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages


def connexion(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username = username, password = password)
        if user is not None:
            login(request,user)
            return redirect('article_list')
        
        else:
            messages.error(request,'Login ou mot de passe incorrecte')
            return redirect('login')


    return render(request,'login.html')


# Deconnexion
def deconnexion(request):
    logout(request)
    return redirect('login')

app/templates/article.html
{% load static %}
{% block article %} 
    {% for article in articles %}
        <article class="col-12 col-md-6 tm-post">
            <hr class="tm-hr-primary">
            <a href="{% url 'article_detail' article.pk %}" class="effect-lily tm-post-link tm-pt-60">
                <div class="tm-post-link-inner">
                    {% if article.image %}
                        <img class="card-img-top" src="{{ article.image.url }}" alt="Image de {{ article.titre }}"  style="width:300px;height:300px;float:center">
                    {% else %}
                        <img class="card-img-top" src="{% static 'img/default.jpg' %}" alt="Image par défaut">
                    {% endif %}
                </div>
                <span class="position-absolute tm-new-badge">Nouveauté</span>
                <h2 class="tm-pt-30 tm-color-primary tm-post-title">{{ article.titre }}</h2>
            </a>
            <p class="tm-pt-30">
               {{ article.contenu|truncatewords:20 }}...
            </p>
            <div class="d-flex justify-content-between tm-pt-45">
                <span class="tm-color-primary">Auteur: {{ article.auteur }} </span>
                <span class="tm-color-primary">Publication: {{ article.date_publication|date:"d M Y" }}</span>
            </div>
            <a href="{% url 'article_detail' article.pk %}" class="tm-btn tm-btn-primary mt-3">Détail</a>
            <hr>
        </article>
    {% endfor %}
{% endblock %}

app/templates/aside.html
<!-- Search form and user actions -->
<div class="row tm-row">
    <!-- User actions -->
    <div class="col-12 d-flex justify-content-between align-items-center">
      <!-- User profile and logout button -->
      {% if request.user.is_authenticated %}
        <div class="d-flex align-items-center">
          <a href="{% url 'logout' %}" class="text-decoration-none">
            <button type="button" class="btn btn-outline-primary">Se Déconnecter</button>
          </a>
          <i class="fas fa-users-cog fa-4x tm-color-primary ml-2"></i>
          <span class="ml-2">Bonjour {{ request.user.username }}</span>
        </div>
      {% else %}
        <!-- Login button -->
        <a href="{% url 'login' %}" class="text-decoration-none">
          <button type="button" class="btn btn-outline-info">Se Connecter</button>
        </a>
      {% endif %}
    </div>
  </div>

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog professionnel</title>
    <link rel="stylesheet" href=" {% static 'fontawesome/css/all.min.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap"
      rel="stylesheet"
    />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/templatemo-xtra-blog.css' %}" rel="stylesheet" />
    <link rel="shortcut icon" href="{% static 'assets/images/logo.png' %}" />

    <link rel="stylesheet" href="{% static 'font/bootstrap-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'font/bootstrap-icons.min.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'font/bootstrap-icons.min.scss' %}"
    />
  </head>
  <body>

    {% block header %}
     {% include 'header.html'%}
     {% endblock %}

    <div class="container-fluid">
      <main class="tm-main">
      
        {% block aside %} 
            
        {% endblock %}
          
        {% block corps %}

        <div class="row tm-row">
           {% block article %}
            {% endblock %}
           {% endblock %}
        </div>

        {% block pagination %} 
        {% endblock %}
         {% block footer %}
          {% include 'footer.html'%} 
        {% endblock %}
      </main>
    </div>
    <script src=" {% static 'js/jquery.min.js' %}"></script>
    <script src=" {% static 'js/templatemo-script.js' %}"></script>
  </body>
</html>

app/templates/creer.html
{% extends 'base.html' %}
{% load static %}

{% block corps %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-lg border-0">
                <div class="card-header bg-primary text-white text-center">
                    <h3>Créer un Nouvel Article</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="id_titre" class="form-label"><strong>Titre de l'article</strong></label>
                            {{ form.titre }}
                        </div>

                        <div class="mb-3">
                            <label for="id_contenu" class="form-label"><strong>Contenu</strong></label>
                            {{ form.contenu }}
                        </div>
                        <div class="mb-3">
                            <label for="id_contenu" class="form-label"><strong>Auteur</strong></label>
                            {{ form.auteur }}
                        </div>

                        <div class="mb-3">
                            <label for="id_image" class="form-label"><strong>Image de l'article</strong></label>
                            {{ form.image }}
                        </div>

                        <div class="d-flex justify-content-between">
                            <a href="{% url 'article_list' %}" class="btn btn-secondary">Annuler</a>
                            <button type="submit" class="btn btn-success">Publier</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block recherche %}
    <h2 class="tm-pt-30 tm-color-primary tm-post-title">Détail de la publication</h2>
{% endblock %}

{% block corps %}
<div class="row tm-row">
    <div class="col-12">
        <hr class="tm-hr-primary tm-mb-55">
        {% if article.image %}
            <img src="{{ article.image.url }}" alt="{{ article.titre }}" class="tm-mb-40" width="954" height="535">
        {% else %}
            <img src="{% static 'img/default.jpg' %}" alt="Image par défaut" class="tm-mb-40" width="954" height="535">
        {% endif %}
    </div>
</div>

<div class="row tm-row">
    <div class="col-lg-8 tm-post-col">
        <div class="tm-post-full">
            <div class="mb-4">
                <h2 class="pt-2 tm-color-primary tm-post-title">{{ article.titre }}</h2>

                <p>{{ article.contenu }}</p>
                <hr>
                 <p class="tm-mb-40">Publié le {{ article.date_publication|date:"d M Y" }} par
                    <b><span>{{ article.auteur }}</span></b>
                </p>

            </div>
        </div>
    </div>

</div>

{% if request.user == article.auteur or request.user.is_superuser %}
    <div class="d-flex justify-content-end">
        <a href="{% url 'article_edit' article.pk %}" class="btn btn-warning mr-2">Modifier</a>
        <a href="{% url 'article_delete' article.pk %}" class="btn btn-danger">Supprimer</a>
    </div>
{% endif %}
    {% comment %} <div class="d-flex justify-content-end">
        <a href="{% url 'article_edit' article.pk %}" class="btn btn-warning mr-2">Modifier</a>
        <a href="{% url 'article_delete' article.pk %}" class="btn btn-danger">Supprimer</a>
    </div> {% endcomment %}
{% endblock %}

app/templates/footer.html
 {% block footer %} 
 <footer class="row tm-row">
                <hr class="col-12">
                <div class="col-md-6 col-12 tm-color-gray">
                    Creer par: <a rel="nofollow" target="_parent" href="#" class="tm-external-link">ansoumane michel</a>
                </div>
                <div class="col-md-6 col-12 tm-color-gray tm-copyright">
                    Copyright 2025 MICDA
                </div>
</footer>
{% endblock %}

app/templates/header.html
	{% comment %} Le header le menu à gauche du site {% endcomment %}
    <header class="tm-header" id="tm-header">
        <div class="tm-header-wrapper">
            <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="tm-site-header">
                <div class="mb-3 mx-auto tm-site-logo"><i class="fas fa-book fa-2x"></i></div> 
                <a href="#" class="tm-nav-link">           
                <h4 class="text-center">Sama Blog</h4>
                </a>
            </div>
            <nav class="tm-nav" id="tm-nav">            
                <ul>
                    <li class="tm-nav-item active"><a href="{% url 'article_list' %}" class="tm-nav-link">
                        <i class="fas fa-home"></i>
                        Blog
                    </a></li>

                    {% comment %} <li class="tm-nav-item"><a href="{% url 'article_new' %}" class="tm-nav-link">
                        <i class="fas fa-pen"></i>
                        Créez Un Article
                    </a></li> {% endcomment %}
                    {% if request.user.is_authenticated %}
                    <li class="tm-nav-item {% if request.resolver_match.url_name == 'article_new' %}active{% endif %}">
                        <a href="{% url 'article_new' %}" class="tm-nav-link">
                            <i class="fas fa-pen"></i>
                            Créez Un Article
                        </a>
                    </li>
                {% endif %}
                    
                </ul>
            </nav>

        </div>
    </header>

app/templates/modifier.html
{% extends 'base.html' %}
{% load static %}

{% block corps %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-lg border-0">
                <div class="card-header bg-primary text-white text-center">
                    <h3>Modifier l'Article</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="mb-3">
                            <label for="id_titre" class="form-label"><strong>Titre de l'article</strong></label>
                            {{ form.titre }}
                        </div>

                        <div class="mb-3">
                            <label for="id_contenu" class="form-label"><strong>Contenu</strong></label>
                            {{ form.contenu }}
                        </div>
                        <div class="mb-3">
                            <label for="id_contenu" class="form-label"><strong>Auteur</strong></label>
                            {{ form.auteur }}
                        </div>

                        <div class="mb-3">
                            <label for="id_image" class="form-label"><strong>Image de l'article</strong></label>
                            {{ form.image }}
                        </div>

                        <div class="d-flex justify-content-between">
                            <a href="{% url 'article_detail' article.pk %}" class="btn btn-secondary">Annuler</a>
                            <button type="submit" class="btn btn-success">Modifier</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/pagination.html
{% block pagination %}
    <div class="row tm-row tm-mt-100 tm-mb-75">
        <div class="tm-paging-wrapper">
            <nav class="tm-paging-nav d-inline-block">
                {% if is_paginated %}
                    <ul>
                        {% if page_obj.has_previous %}
                            <li class="tm-paging-item">
                                <a href="?page={{ page_obj.previous_page_number }}" tabindex="-1"
                                   class="mb-2 tm-btn tm-btn-primary tm-prev-next tm-mr-20">Précédent</a>
                            </li>
                        {% endif %}

                        {% if page_obj.has_previous %}
                            <li class="tm-paging-item">
                                <a href="?page={{ page_obj.previous_page_number }}"
                                   class="mb-2 tm-btn tm-paging-link">{{ page_obj.previous_page_number }}</a>
                            </li>
                        {% endif %}

                        <li class="tm-paging-item active">
                            <a href="#" class="mb-2 tm-btn tm-paging-link">{{ page_obj.number }}</a>
                        </li>

                        {% if page_obj.has_next %}
                            <li class="tm-paging-item">
                                <a href="?page={{ page_obj.next_page_number }}"
                                   class="mb-2 tm-btn tm-paging-link">{{ page_obj.next_page_number }}</a>
                            </li>
                        {% endif %}

                        {% if page_obj.has_next %}
                            <li class="tm-paging-item">
                                <a href="?page={{ page_obj.next_page_number }}" class="mb-2 tm-btn tm-btn-primary tm-prev-next">Suivant</a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            </nav>
        </div>
    </div>
{% endblock %}

app/templates/post.html
{% extends 'base.html'%}

{% block  aside %} 
            {% include 'aside.html'%}
{% endblock %}

{% block article  %} 
{% if messages %}
	{% for message in messages %}
		<h5 class="alert alert-danger" role="alert">
			{{ message }}
		</h5>
	{% endfor %}
{% endif %}
            {% include 'article.html'%}
{% endblock %}

{% block pagination %} 
    {% include 'pagination.html'%}
{% endblock %}

app/templates/supprimer.html
{% extends 'base.html' %}
{% load static %}
{% block corps %}

    <h2>Voulez-vous vraiment supprimer "{{ article.titre }}" ?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Supprimer</button>
        <a href="{% url 'article_detail' article.pk %}" class="btn btn-secondary">Annuler</a>

    </form>
{% endblock %}

users/templates/creation.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

		<!-- Meta -->
		<meta name="description" content="Responsive Bootstrap 5 Admin Dashboards" />
		<meta name="author" content="Bootstrap Gallery" />
		<link rel="canonical" href="https://www.bootstrap.gallery/">
		<meta property="og:url" content="https://www.bootstrap.gallery">
		<meta property="og:title" content="Admin Templates - Dashboard Templates | Bootstrap Gallery">
		<meta property="og:description" content="Marketplace for Bootstrap Admin Dashboards">
		<meta property="og:type" content="Website">
		<meta property="og:site_name" content="Bootstrap Gallery">
		<link rel="shortcut icon" href="{% static 'assets/logo.png' %}" />

		<!-- Title -->
		<title>Création de compte</title>

		<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}" />

		<!-- Icomoon Font Icons css -->
		<link rel="stylesheet" href="{% static 'assets/fonts/icomoon/icomoon.css' %}" />

		<!-- Main css -->
		<link rel="stylesheet" href="{% static 'assets/css/main.min.css' %}" />
	</head>

	<body class="login-container">


		<!-- Login box start -->
		<div class="container">
		
			<form method='post' enctype="multipart/form-data">
			{% if messages %}
				{% for message in messages %}
					<h5 class="alert alert-danger" role="alert">
						{{ message }}
					</h5>
				{% endfor %}
			{% endif %}
			{% csrf_token %}
				<div class="login-box">
					<div class="login-blocks-img"></div>
					<div class="login-form">
						<a href="#" class="login-logo">
							<img src="{% static 'assets/logo.png' %}" alt="piergyDeveloppement logo" />
						</a>
						<div class="login-welcome">
							Bienvenue, Créez un compte<i>Cher(e) ami(e)</i>, moins de 2 minutes.
						</div>
						<div class="login-form-block">
							<label class="login-form-label">Nom d'utilisateur</label>
							<input type="text" class="login-form-control" name="username" required/>
						</div>
						<div class="login-form-block">
							<label class="login-form-label">Email</label>
							<input type="mail" class="login-form-control" name="email" required />
						</div>
						<div class="login-form-block">
							<label class="login-form-label">Mot de passe</label>
							<input type="password" class="login-form-control" name="password" required />
						</div>
						
						<div class="login-form-block">
							<label class="login-form-label">Confirmer</label>
							<input type="password" class="login-form-control" name="password_confirm" required />
						</div>
						<div class="login-form-actions">
							<button type="submit" class="btn">
								<span class="icon"> <i class="icon-login"></i> </span> Valider
							</button>
							<br />
						</div>

						<div class="login-form-footer">
							<div class="additional-link">
								Vous avez déjà un compte ?
								<a href="{% url 'login' %}" class="btn"> Se connecter</a>
							</div>
						</div>

					</div>
				</div>
			</form>
		</div>
		
		<script src="{% static 'assets/js/jquery.min.js' %}"></script>


		<script src="{% static 'assets/js/main.js' %}"></script>
	</body>

</html>

users/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Meta -->
    {% comment %}
    <meta
      name="description"
      content="Responsive Bootstrap 5 Admin Dashboards"
    />
    {% endcomment %}
    <meta name="author" content="Bootstrap Gallery" />
    <link rel="canonical" href="https://www.bootstrap.gallery/" />
    <meta property="og:url" content="https://www.bootstrap.gallery" />
    <meta
      property="og:title"
      content="Admin Templates - Dashboard Templates | Bootstrap Gallery"
    />
    <meta
      property="og:description"
      content="Marketplace for Bootstrap Admin Dashboards"
    />
    <meta property="og:type" content="Website" />
    <meta property="og:site_name" content="Bootstrap Gallery" />
    <link rel="shortcut icon" href="{% static 'assets/logo.png' %}" />

    <title>Se Connecter</title>

    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}" />

    <!-- Icomoon Font Icons css -->
    <link
      rel="stylesheet"
      href="{% static 'assets/fonts/icomoon/icomoon.css' %}"
    />

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'assets/css/main.min.css' %}" />
  </head>

  <body class="login-container">
    <!-- Login box start -->
    <div class="container">
      <form method="post">
        {% if messages %} {% for message in messages %}
        <h5 class="alert alert-danger" role="alert">{{ message }}</h5>
        {% endfor %} {% endif %} {% csrf_token %}
        <div class="login-box">
          <div class="login-blocks-img"></div>
          <div class="login-form">
            <div class="login-form-block">
              <label class="login-form-label">Nom d'utilisateur</label>
              <input
                type="text"
                class="login-form-control"
                name="username"
                required
              />
            </div>
            <div class="login-form-block">
              <label class="login-form-label">Mot de passe</label>
              <input
                type="password"
                class="login-form-control"
                name="password"
                required
              />
            </div>
            <div class="login-form-actions">
              <button type="submit" class="btn">
                <span class="icon"> <i class="icon-login"></i> </span> Se
                Connecter
              </button>
            </div>
            
          </div>
        </div>
      </form>
    </div>

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>

    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>